const API_URL=window.FADILA_API_URL;
const el=id=>document.getElementById(id);let currentUser=null,sessionUser=null,customerServices=[],customerAppointments=[];
const token=()=>localStorage.getItem('token');
const api=async(path,options={})=>{options.headers={...(options.headers||{}),...(token()?{Authorization:`Bearer ${token()}`}:{})};const response=await fetch(`${API_URL}${path}`,options);const data=await response.json().catch(()=>({}));if(response.status===401)logout();if(!response.ok)throw new Error(data.error||'حدث خطأ');return data};
function message(id,text,type=''){el(id).textContent=text;el(id).className=`message ${type}`}
async function login(){try{const data=await api('/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:el('username').value,password:el('password').value})});localStorage.setItem('token',data.token);sessionUser=data.user;if(data.user.role==='owner'){sessionStorage.setItem('skipDashboardIntro','1');return location.href='dashboard.html'}await showCustomer(data.user)}catch(error){message('loginMessage',error.message,'error')}}
async function syncExistingPushSubscription(){try{if(!token()||!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window)||Notification.permission!=='granted')return;const registration=await navigator.serviceWorker.ready,subscription=await registration.pushManager.getSubscription();if(subscription)await api('/push/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subscription})})}catch(error){console.error('Push account sync failed:',error)}}
async function logout(){const savedToken=token();try{if(savedToken&&'serviceWorker'in navigator){const registration=await navigator.serviceWorker.ready,subscription=await registration.pushManager.getSubscription();if(subscription)await fetch(`${API_URL}/push/subscribe`,{method:'DELETE',headers:{Authorization:`Bearer ${savedToken}`,'Content-Type':'application/json'},body:JSON.stringify({endpoint:subscription.endpoint}),keepalive:true})}}catch(error){console.error('Push logout cleanup failed:',error)}finally{localStorage.removeItem('token');location.href='index.html'}}
async function enterApp(){const welcome=el('welcomeView');welcome.classList.add('welcome-leaving');await new Promise(resolve=>setTimeout(resolve,360));welcome.classList.add('hidden');el('appContent').classList.remove('hidden');if(sessionUser){if(sessionUser.role==='owner'){sessionStorage.setItem('skipDashboardIntro','1');return location.href='dashboard.html'}return showCustomer(sessionUser)}el('loginView').classList.remove('hidden')}
async function showCustomer(user){currentUser=user;el('loginView').classList.add('hidden');el('customerView').classList.remove('hidden');el('messagesButton').classList.remove('hidden');el('customerRefreshButton').classList.remove('hidden');el('welcome').textContent=`مرحباً ${user.name}`;await syncExistingPushSubscription();await Promise.all([loadServices(),loadAppointments(),loadMessages()]);updateNotificationState()}
async function refreshCustomerData(){const button=el('customerRefreshButton');button.disabled=true;button.classList.add('is-refreshing');try{await Promise.all([loadServices(),loadAppointments(),loadMessages()])}catch(error){alert(error.message)}finally{button.disabled=false;button.classList.remove('is-refreshing')}}
async function loadServices(){customerServices=await api('/services');el('service').innerHTML='<option value="">اختر خدمة</option>'+customerServices.map(s=>`<option value="${escapeHtml(s.name)}">${escapeHtml(s.name)} — ₪${s.price}</option>`).join('')}
async function loadSlots(){const date=el('date').value,service=el('service').value;if(!date||!service)return;const data=await api(`/appointments/available/${date}?service=${encodeURIComponent(service)}`);el('time').innerHTML='<option value="">اختر ساعة</option>'+data.availableSlots.map(t=>`<option>${t}</option>`).join('');el('time').disabled=!data.availableSlots.length}
async function book(){try{await api('/appointments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({service:el('service').value,date:el('date').value,time:el('time').value})});message('bookingMessage','تم إرسال الطلب إلى صاحب المحل','success');await loadAppointments()}catch(error){message('bookingMessage',error.message,'error')}}
async function loadAppointments(){const data=await api('/appointments');customerAppointments=data.data;el('appointments').innerHTML=data.data.length?data.data.map(a=>{const pending=a.changeRequest?.status==='pending',canRequest=!['cancelled','completed','no-show'].includes(a.status);return`<article class="appointment ${a.status}"><strong>${escapeHtml(a.service)}</strong><p>${new Date(a.date).toLocaleDateString('ar',{timeZone:'Asia/Jerusalem'})} الساعة ${a.time}</p><p>الحالة: ${statusLabel(a.status)}</p>${a.notes?`<p>${escapeHtml(a.notes)}</p>`:''}${pending?`<div class="customer-change-request pending"><strong>طلب التعديل قيد المراجعة</strong><p>${escapeHtml(a.changeRequest.requestedService)} · ${escapeHtml(a.changeRequest.requestedDate)} · ${escapeHtml(a.changeRequest.requestedTime)}</p>${a.changeRequest.text?`<p>${escapeHtml(a.changeRequest.text)}</p>`:''}</div>`:''}${canRequest&&!pending?`<button class="secondary change-request-toggle" type="button" onclick="toggleChangeRequest('${a._id}')">طلب تعديل الموعد</button><div id="change-request-${a._id}" class="change-request-form hidden"></div>`:''}</article>`}).join(''):'<p class="muted">لا توجد مواعيد بعد</p>'}
function prepareChangeRequestForm(id){const form=el('change-request-'+id),a=customerAppointments.find(item=>item._id===id);if(!form||!a||form.dataset.ready)return;const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem'}).format(new Date(a.date)),options=customerServices.map(s=>`<option value="${escapeHtml(s.name)}" ${s.name===a.service?'selected':''}>${escapeHtml(s.name)} — ${s.duration} دقيقة</option>`).join('');form.innerHTML=`<label>الخدمة المطلوبة<select id="change-request-service-${id}">${options}</select></label><div class="grid-two"><label>التاريخ المطلوب<input id="change-request-date-${id}" type="date" value="${date}"></label><label>الساعة المطلوبة<input id="change-request-time-${id}" type="time" step="300" value="${escapeHtml(a.time)}"></label></div><label>ملاحظة اختيارية<textarea id="change-request-text-${id}" maxlength="500" rows="3" placeholder="اكتب أي تفاصيل إضافية"></textarea></label><button type="button" onclick="sendChangeRequest('${id}')">إرسال الطلب</button><p id="change-request-message-${id}" class="message"></p>`;form.dataset.ready='1'}
function toggleChangeRequest(id){prepareChangeRequestForm(id);el('change-request-'+id).classList.toggle('hidden')}
async function sendChangeRequest(id){const text=el('change-request-text-'+id).value.trim(),service=el('change-request-service-'+id).value,date=el('change-request-date-'+id).value,time=el('change-request-time-'+id).value;try{await api(`/appointments/${id}/change-request`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,service,date,time})});message('change-request-message-'+id,'تم إرسال طلب التعديل إلى صاحب المحل','success');await loadAppointments()}catch(error){message('change-request-message-'+id,error.message,'error')}}
function statusLabel(s){return({pending:'بانتظار الموافقة',confirmed:'مؤكد',cancelled:'ملغي',completed:'مكتمل','no-show':'لم يحضر'})[s]||s}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function urlBase64ToUint8Array(value){const padding='='.repeat((4-value.length%4)%4),base64=(value+padding).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function enablePush(){try{if(!window.isSecureContext)throw new Error('تتطلب الإشعارات اتصال HTTPS آمناً');if(!window.FadilaPwa?.isStandalone())throw new Error('يجب فتح Fadila من الأيقونة على الشاشة الرئيسية');if(!('serviceWorker'in navigator)||!('Notification'in window)||!('PushManager'in window))throw new Error('إصدار الجهاز أو المتصفح لا يدعم الإشعارات');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('يرجى السماح بالإشعارات من إعدادات الجهاز');const registration=await navigator.serviceWorker.ready;const {publicKey}=await api('/push/public-key');if(!publicKey)throw new Error('لم يتم إعداد مفاتيح الإشعارات على الخادم بعد');let subscription=await registration.pushManager.getSubscription();subscription=subscription||await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(publicKey)});await api('/push/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subscription})});updateNotificationState();}catch(error){console.error('Push setup failed:',error);el('notificationState').textContent=error.message||'تعذر تفعيل الإشعارات على هذا الجهاز'}}
async function testPush(){try{const data=await api('/push/test',{method:'POST'});el('notificationState').textContent=data.sent>0?'✅ تم إرسال إشعار تجريبي':'لا يوجد اشتراك نشط. فعّل الإشعارات أولاً.'}catch(error){el('notificationState').textContent=error.message}}
function updateNotificationState(){if('Notification'in window&&Notification.permission==='granted'){el('notificationState').textContent='✅ الإشعارات مفعّلة على هذا الجهاز';el('enableNotifications').classList.add('hidden')}}
async function loadMessages(){try{const data=await api('/messages');el('messagesBadge').textContent=data.unreadCount>99?'99+':String(data.unreadCount);el('messagesBadge').classList.toggle('hidden',!data.unreadCount);el('messagesList').innerHTML=data.data.length?data.data.map(item=>`<article class="message-item ${item.readAt?'':'unread'}"><div><h3>${escapeHtml(item.title)}</h3><time>${new Date(item.createdAt).toLocaleString('ar',{timeZone:'Asia/Jerusalem'})}</time></div><p>${escapeHtml(item.body)}</p></article>`).join(''):'<p class="muted empty-messages">لا توجد رسائل بعد</p>'}catch(error){console.error('Messages load failed:',error)}}
async function openMessages(){await loadMessages();el('messagesPanel').classList.remove('hidden');document.body.classList.add('messages-open');try{await api('/messages/read-all',{method:'PUT'});el('messagesBadge').classList.add('hidden');el('messagesList').querySelectorAll('.unread').forEach(item=>item.classList.remove('unread'))}catch(error){console.error('Mark messages read failed:',error)}}
function closeMessages(){el('messagesPanel').classList.add('hidden');document.body.classList.remove('messages-open')}
document.addEventListener('DOMContentLoaded',async()=>{el('date').min=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jerusalem'});el('enterButton').onclick=enterApp;el('loginButton').onclick=login;el('logoutButton').onclick=logout;el('messagesButton').onclick=openMessages;el('customerRefreshButton').onclick=refreshCustomerData;el('closeMessages').onclick=closeMessages;el('messagesPanel').addEventListener('click',event=>{if(event.target===el('messagesPanel'))closeMessages()});navigator.serviceWorker?.addEventListener('message',event=>{if(event.data?.type==='fadila-message'&&currentUser)loadMessages()});el('enableNotifications').onclick=enablePush;el('testNotification').onclick=testPush;el('service').onchange=loadSlots;el('date').onchange=loadSlots;el('bookButton').onclick=book;if(token()){try{const data=await api('/auth/me');sessionUser=data.user}catch{sessionUser=null}}});
