const API=window.FADILA_API_URL,token=localStorage.getItem('token');if(!token)location.href='admin.html';const $=id=>document.getElementById(id);let customers=[],services=[],appointments=[];
let existingPushSynced=false;
async function api(path,options={}){options.headers={...(options.headers||{}),Authorization:`Bearer ${token}`};const r=await fetch(API+path,options),d=await r.json().catch(()=>({}));if(r.status===401){localStorage.removeItem('token');location.href='admin.html'}if(!r.ok){const error=new Error(d.error||'حدث خطأ');error.requiresManualEdit=d.requiresManualEdit===true;throw error}return d}
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const msg=(id,text,type='')=>{$(id).textContent=text;$(id).className=`message ${type}`};
async function loadCustomers(){const d=await api('/auth/customers');customers=d.data;const customerOptions=customers.map(c=>`<option value="${c.id}">${safe(c.name)} — ${safe(c.phone)}</option>`).join('');$('manualCustomer').innerHTML='<option value="">اختر زبوناً</option>'+customerOptions;$('notificationCustomer').innerHTML='<option value="">اختر المستلم</option><option value="__all__">📣 جميع الزبائن</option>'+customerOptions}
async function createCustomer(){try{await api('/auth/customers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('customerName').value,phone:$('customerPhone').value,username:$('customerUsername').value,password:$('customerPassword').value})});msg('customerMessage','تم إنشاء الحساب بنجاح','success');['customerName','customerPhone','customerUsername','customerPassword'].forEach(id=>$(id).value='');await loadCustomers()}catch(e){msg('customerMessage',e.message,'error')}}
async function loadServices(){services=await api('/services');const options='<option value="">اختر خدمة</option>'+services.map(s=>`<option value="${safe(s.name)}">${safe(s.name)} — ${s.duration} دقيقة</option>`).join('');$('manualService').innerHTML=options;$('services').innerHTML=services.map(s=>`<div class="appointment row-between"><span>${safe(s.name)} — ₪${s.price}، ${s.duration} دقيقة</span><button class="danger compact" onclick="deleteService('${s._id}')">حذف</button></div>`).join('');if(appointments.length){renderAppointments();decorateAllAppointmentDates()}}
async function addService(){await api('/services',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('serviceName').value,price:Number($('servicePrice').value),duration:Number($('serviceDuration').value)})});await loadServices()}
async function deleteService(id){if(confirm('هل تريد حذف الخدمة؟')){await api('/services/'+id,{method:'DELETE'});await loadServices()}}
async function loadSlots(){const date=$('manualDate').value,service=$('manualService').value;if(!date||!service)return;const d=await api(`/appointments/available/${date}?service=${encodeURIComponent(service)}`);$('manualTime').innerHTML='<option value="">اختر ساعة</option>'+d.availableSlots.map(t=>`<option>${t}</option>`).join('');$('manualTime').disabled=!d.availableSlots.length}
async function createAppointment(){try{await api('/appointments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerId:$('manualCustomer').value,service:$('manualService').value,date:$('manualDate').value,time:$('manualTime').value})});msg('manualMessage','تم إنشاء الموعد وإرسال إشعار للزبون','success');await loadAppointments()}catch(e){msg('manualMessage',e.message,'error')}}
const statusOptions=a=>['pending','confirmed','cancelled','completed','no-show'].map(s=>`<option value="${s}" ${a.status===s?'selected':''}>${statusLabel(s)}</option>`).join('');
function getTodayInJerusalem(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
async function loadAppointments(){const d=await api('/appointments');appointments=d.data;renderAppointments();decorateAllAppointmentDates()}
function renderAppointments(){const date=$('filterDate').value;const list=date?appointments.filter(a=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem'}).format(new Date(a.date))===date):appointments;$('appointments').innerHTML=list.length?list.map(a=>{const appointmentDate=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem'}).format(new Date(a.date)),serviceOptions=services.map(s=>`<option value="${safe(s.name)}" ${s.name===a.service?'selected':''}>${safe(s.name)} — ${s.duration} دقيقة</option>`).join('');return`<article class="appointment compact-appointment ${a.status}" id="appointment-${a._id}"><div class="appointment-summary"><time>${safe(a.time)}</time><div class="appointment-summary-text"><strong>${safe(a.customerName)}</strong><span>${safe(a.service)}</span></div><span class="appointment-status">${safe(statusLabel(a.status))}</span><button class="secondary appointment-edit-toggle" type="button" onclick="toggleAppointmentEditor('${a._id}',this)" aria-expanded="false">تعديل</button></div><div class="appointment-editor hidden" id="editor-${a._id}"><div class="grid-two appointment-schedule-edit"><label>التاريخ<input id="date-${a._id}" type="date" value="${appointmentDate}"></label><label>الساعة<input id="time-${a._id}" type="time" value="${safe(a.time)}"></label><label>نوع الخدمة<select id="service-${a._id}">${serviceOptions}</select></label><label>الحالة<select id="status-${a._id}">${statusOptions(a)}</select></label><label>ملاحظة<input id="notes-${a._id}" value="${safe(a.notes||'')}"></label></div><div class="appointment-actions"><button onclick="updateAppointment('${a._id}')">حفظ وإرسال إشعار</button><button class="danger" onclick="deleteAppointment('${a._id}')">حذف الموعد</button></div></div></article>`}).join(''):'<p class="muted">لا توجد مواعيد</p>'}
function updateAppointmentFilterControls(){$('showAllAppointments').textContent=$('filterDate').value?'عرض كل المواعيد':'عرض مواعيد اليوم';$('timelineEditorButton').disabled=!$('filterDate').value}
function decorateAllAppointmentDates(){appointments.forEach(a=>{const card=$('appointment-'+a._id),detail=card?.querySelector('.appointment-summary-text span');if(!$('filterDate').value&&detail)detail.textContent+=` · ${new Date(a.date).toLocaleDateString('ar',{timeZone:'Asia/Jerusalem'})}`;if(card&&a.changeRequest?.status==='pending'&&!card.querySelector('.owner-change-request'))card.querySelector('.appointment-summary').insertAdjacentHTML('afterend',`<div class="owner-change-request"><strong>طلب تعديل من الزبون</strong><p><b>الخدمة:</b> ${safe(a.changeRequest.requestedService||'غير محددة')} · <b>التاريخ:</b> ${safe(a.changeRequest.requestedDate||'غير محدد')} · <b>الساعة:</b> ${safe(a.changeRequest.requestedTime||'غير محددة')}</p>${a.changeRequest.text?`<p>${safe(a.changeRequest.text)}</p>`:''}<div class="change-request-actions"><button type="button" onclick="resolveChangeRequest('${a._id}','approved')">موافقة وتحديث</button><button type="button" class="danger" onclick="resolveChangeRequest('${a._id}','rejected')">رفض</button><button type="button" class="secondary" onclick="openPartialChangeEdit('${a._id}')">تعديل جزئي</button></div></div>`)})}
function toggleAllAppointments(){if($('filterDate').value)$('filterDate').value='';else $('filterDate').value=getTodayInJerusalem();updateAppointmentFilterControls();renderAppointments();decorateAllAppointmentDates()}
function statusLabel(status){return({pending:'بانتظار الموافقة',confirmed:'مؤكد',cancelled:'ملغي',completed:'مكتمل','no-show':'لم يحضر'})[status]||status}
function toggleAppointmentEditor(id,button){const editor=$('editor-'+id),open=editor.classList.contains('hidden');editor.classList.toggle('hidden',!open);button.textContent=open?'إغلاق':'تعديل';button.setAttribute('aria-expanded',String(open))}
async function updateAppointment(id){try{await api('/appointments/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({service:$('service-'+id).value,date:$('date-'+id).value,time:$('time-'+id).value,status:$('status-'+id).value,notes:$('notes-'+id).value})});await loadAppointments();await loadOwnerMessages()}catch(e){alert(e.message)}}
async function deleteAppointment(id){const a=appointments.find(x=>x._id===id);if(!a||!confirm(`هل تريد حذف موعد ${a.customerName}؟ سيتلقى الزبون إشعار إلغاء.`))return;try{await api('/appointments/'+id,{method:'DELETE'});await loadAppointments()}catch(e){alert(e.message)}}
async function resolveChangeRequest(id,decision){const label=decision==='approved'?'الموافقة وتحديث الموعد':'الرفض';if(!confirm(`تأكيد ${label}؟`))return;try{await api(`/appointments/${id}/change-request`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision})});await loadAppointments();await loadOwnerMessages()}catch(e){alert(e.message);if(e.requiresManualEdit)openPartialChangeEdit(id)}}
function openPartialChangeEdit(id){const a=appointments.find(item=>item._id===id);if(!a)return alert('لم يتم العثور على الموعد');const requestedDate=a.changeRequest?.requestedDate||new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem'}).format(new Date(a.date));if($('filterDate').value!==requestedDate){$('filterDate').value=requestedDate;updateAppointmentFilterControls();renderAppointments();decorateAllAppointmentDates()}const card=$('appointment-'+id),toggle=card?.querySelector('.appointment-edit-toggle'),editor=$('editor-'+id),notes=$('notes-'+id);closeOwnerMessages();if(toggle&&editor?.classList.contains('hidden'))toggleAppointmentEditor(id,toggle);if(a.changeRequest?.status==='pending'){if(a.changeRequest.requestedDate)$('date-'+id).value=a.changeRequest.requestedDate;if(a.changeRequest.requestedTime)$('time-'+id).value=a.changeRequest.requestedTime;if(a.changeRequest.requestedService)$('service-'+id).value=a.changeRequest.requestedService;if(notes&&a.changeRequest.text&&!notes.value)notes.value=a.changeRequest.text}if(notes){notes.placeholder='اكتب للزبون تفاصيل التعديل الذي تقترحه';notes.focus()}card?.scrollIntoView({behavior:'smooth',block:'center'})}
const TIMELINE_START=7,TIMELINE_END=24,TIMELINE_PX_PER_HOUR=72;
function minutesFromTime(time){const [hours,minutes]=time.split(':').map(Number);return hours*60+minutes}
function timeFromMinutes(total){return`${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}
function appointmentsForSelectedDate(){const date=$('filterDate').value;return appointments.filter(a=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem'}).format(new Date(a.date))===date&&a.status!=='cancelled')}
function openTimeline(){const date=$('filterDate').value;if(!date)return alert('يرجى اختيار تاريخ');$('timelineDateLabel').textContent=new Date(`${date}T12:00:00`).toLocaleDateString('ar',{weekday:'long',day:'numeric',month:'long',year:'numeric'});renderTimeline();$('timelineModal').classList.remove('hidden');document.body.classList.add('timeline-open');const first=appointmentsForSelectedDate().sort((a,b)=>a.time.localeCompare(b.time))[0];$('timelineScroll').scrollTop=first?Math.max(0,(minutesFromTime(first.time)-TIMELINE_START*60)/60*TIMELINE_PX_PER_HOUR-70):0}
function closeTimeline(){ $('timelineModal').classList.add('hidden');document.body.classList.remove('timeline-open') }
function renderTimeline(){const grid=$('timelineGrid'),height=(TIMELINE_END-TIMELINE_START)*TIMELINE_PX_PER_HOUR,totalTicks=(TIMELINE_END-TIMELINE_START)*12;grid.style.height=`${height}px`;const ticks=Array.from({length:totalTicks+1},(_,i)=>{const totalMinutes=TIMELINE_START*60+i*5,isHour=i%12===0,isQuarter=i%3===0,label=isHour?`${String(Math.floor(totalMinutes/60)).padStart(2,'0')}:00`:'';return`<div class="timeline-tick ${isHour?'hour':isQuarter?'quarter':'minor'}" style="top:${i*TIMELINE_PX_PER_HOUR/12}px">${label?`<span>${label}</span>`:''}</div>`}).join('');grid.innerHTML=ticks+appointmentsForSelectedDate().map(a=>{const start=minutesFromTime(a.time),itemHeight=Math.max(38,a.duration/60*TIMELINE_PX_PER_HOUR),top=Math.max(0,Math.min(height-itemHeight,(start-TIMELINE_START*60)/60*TIMELINE_PX_PER_HOUR));return`<div class="timeline-appointment ${a.status}" data-id="${a._id}" style="top:${top}px;height:${itemHeight}px"><div class="timeline-appointment-text"><strong>${safe(a.time)} · ${safe(a.customerName)}</strong><span>${safe(a.service)}</span></div><button type="button" data-edit-id="${a._id}">تعديل</button></div>`}).join('');grid.querySelectorAll('.timeline-appointment').forEach(enableTimelineDrag);grid.querySelectorAll('[data-edit-id]').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();closeTimeline();const id=button.dataset.editId,card=$('appointment-'+id),toggle=card?.querySelector('.appointment-edit-toggle');if(toggle&&$('editor-'+id).classList.contains('hidden'))toggleAppointmentEditor(id,toggle);card?.scrollIntoView({behavior:'smooth',block:'center'})}))}
function enableTimelineDrag(block){block.addEventListener('pointerdown',event=>{if(event.target.closest('button'))return;event.preventDefault();const startY=event.clientY,startTop=parseFloat(block.style.top),maxTop=parseFloat($('timelineGrid').style.height)-parseFloat(block.style.height);block.setPointerCapture(event.pointerId);block.classList.add('dragging');const move=moveEvent=>{const raw=Math.max(0,Math.min(maxTop,startTop+moveEvent.clientY-startY)),snap=TIMELINE_PX_PER_HOUR/12;block.style.top=`${Math.round(raw/snap)*snap}px`};const end=async()=>{block.removeEventListener('pointermove',move);block.removeEventListener('pointerup',end);block.removeEventListener('pointercancel',end);block.classList.remove('dragging');const minutes=TIMELINE_START*60+Math.round(parseFloat(block.style.top)/TIMELINE_PX_PER_HOUR*12)*5;await moveAppointmentOnTimeline(block.dataset.id,timeFromMinutes(minutes))};block.addEventListener('pointermove',move);block.addEventListener('pointerup',end);block.addEventListener('pointercancel',end)})}
async function moveAppointmentOnTimeline(id,time){const a=appointments.find(item=>item._id===id),date=$('filterDate').value;$('timelineMessage').textContent='جارٍ حفظ التغيير…';try{await api('/appointments/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({service:a.service,date,time,status:a.status,notes:a.notes||''})});$('timelineMessage').textContent=`✅ تم نقل موعد ${a.customerName} إلى الساعة ${time}`;$('timelineMessage').className='message success';await loadAppointments();renderTimeline()}catch(e){$('timelineMessage').textContent=e.message;$('timelineMessage').className='message error';renderTimeline()}}
const days={sunday:'الأحد',monday:'الإثنين',tuesday:'الثلاثاء',wednesday:'الأربعاء',thursday:'الخميس',friday:'الجمعة',saturday:'السبت'};
async function loadHours(){const d=await api('/settings');$('workingHours').innerHTML=Object.entries(days).map(([key,label])=>{const h=d.workingHours[key];return`<div class="appointment"><strong>${label}</strong><div class="grid-two"><label>الفتح<input id="${key}-start" type="time" value="${h.start||''}"></label><label>الإغلاق<input id="${key}-end" type="time" value="${h.end||''}"></label></div><label><input id="${key}-enabled" type="checkbox" ${h.enabled?'checked':''}> مفتوح</label></div>`}).join('')}
async function saveHours(){const workingHours={};for(const key of Object.keys(days))workingHours[key]={start:$(`${key}-start`).value,end:$(`${key}-end`).value,enabled:$(`${key}-enabled`).checked,breaks:[]};await api('/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({workingHours})});alert('تم الحفظ')}
function b64(v){const p='='.repeat((4-v.length%4)%4),raw=atob((v+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function enablePush(){try{if(!window.isSecureContext)throw new Error('تتطلب الإشعارات اتصال HTTPS آمناً');if(!window.FadilaPwa?.isStandalone())throw new Error('يجب فتح Fadila من الأيقونة على الشاشة الرئيسية');if(!('serviceWorker'in navigator)||!('Notification'in window)||!('PushManager'in window))throw new Error('إصدار الجهاز أو المتصفح لا يدعم الإشعارات');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('يرجى السماح بالإشعارات من إعدادات الجهاز');const reg=await navigator.serviceWorker.ready,{publicKey}=await api('/push/public-key');if(!publicKey)throw new Error('لم يتم إعداد مفاتيح الإشعارات على الخادم بعد');let sub=await reg.pushManager.getSubscription();sub=sub||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(publicKey)});await api('/push/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subscription:sub})});$('notificationState').textContent='✅ الإشعارات مفعّلة';$('enableNotifications').classList.add('hidden')}catch(e){console.error('Push setup failed:',e);$('notificationState').textContent=e.message||'تعذر تفعيل الإشعارات على هذا الجهاز'}}
async function syncExistingOwnerPush(){if(existingPushSynced)return;try{if(!('serviceWorker'in navigator)||!('Notification'in window)||Notification.permission!=='granted')return;const reg=await navigator.serviceWorker.ready,subscription=await reg.pushManager.getSubscription();if(subscription)await api('/push/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subscription})});existingPushSynced=true}catch(e){console.error('Owner push account sync failed:',e)}}
async function logoutOwner(){try{if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.ready,subscription=await reg.pushManager.getSubscription();if(subscription)await fetch(API+'/push/subscribe',{method:'DELETE',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({endpoint:subscription.endpoint}),keepalive:true})}}catch(e){console.error('Owner push logout cleanup failed:',e)}finally{localStorage.removeItem('token');location.href='index.html'}}
document.addEventListener('click',event=>{if(event.target.closest('#logout')){event.preventDefault();event.stopImmediatePropagation();logoutOwner()}},true);
document.addEventListener('click',event=>{if(event.target.closest('#ownerRefreshButton'))refreshOwnerData()});
async function testPush(){try{const data=await api('/push/test',{method:'POST'});$('notificationState').textContent=data.sent>0?'✅ تم إرسال إشعار تجريبي':'لا يوجد اشتراك نشط. فعّل الإشعارات أولاً.'}catch(e){$('notificationState').textContent=e.message}}
async function sendCustomerNotification(){try{const selected=$('notificationCustomer').value,title=$('notificationTitle').value.trim(),body=$('notificationBody').value.trim(),sendToAll=selected==='__all__';if(!selected||!title||!body)throw new Error('يرجى اختيار المستلم وكتابة العنوان والرسالة');if(sendToAll&&!confirm('هل تريد إرسال الإشعار إلى جميع الزبائن النشطين؟'))return;$('sendCustomerNotification').disabled=true;const data=await api('/push/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerId:sendToAll?null:selected,sendToAll,title,body})});if(data.sent>0){const text=sendToAll?`✅ تم إرسال الإشعار إلى ${data.sent} من أجهزة الزبائن`:`✅ تم إرسال الإشعار إلى ${data.sent} من الأجهزة`;msg('sendNotificationMessage',text,'success');$('notificationTitle').value='';$('notificationBody').value=''}else{msg('sendNotificationMessage',sendToAll?'لا توجد أجهزة مسجلة لدى الزبائن':'لا يوجد جهاز مسجل للإشعارات لدى هذا الزبون','error')}}catch(e){msg('sendNotificationMessage',e.message,'error')}finally{$('sendCustomerNotification').disabled=false}}
function messageAppointmentId(item){if(item.appointment)return String(item.appointment);const match=String(item.tag||'').match(/^(?:change-request-|new-)([a-f\d]{24})(?:-|$)/i);return match?.[1]||''}
function isCurrentChangeRequestMessage(item,allMessages){const id=messageAppointmentId(item),appointment=appointments.find(a=>a._id===id);if(!id||appointment?.changeRequest?.status!=='pending')return false;const currentTag=appointment.changeRequest.notificationTag;if(currentTag)return item.tag===currentTag;const newest=allMessages.find(message=>messageAppointmentId(message)===id);return newest?._id===item._id}
function isPendingBookingMessage(item){const id=messageAppointmentId(item),appointment=appointments.find(a=>a._id===id);return /^new-[a-f\d]{24}$/i.test(String(item.tag||''))&&appointment?.status==='pending'}
async function approvePendingAppointment(id){const appointment=appointments.find(item=>item._id===id);if(!appointment||!confirm(`تأكيد موعد ${appointment.customerName}؟`))return;try{const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem'}).format(new Date(appointment.date));await api('/appointments/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({service:appointment.service,date,time:appointment.time,status:'confirmed',notes:appointment.notes||''})});await loadAppointments();await loadOwnerMessages()}catch(e){alert(e.message);openPartialChangeEdit(id)}}
function ownerMessageActions(item,allMessages){const id=messageAppointmentId(item);let actionButtons='';if(isCurrentChangeRequestMessage(item,allMessages))actionButtons=`<button type="button" onclick="resolveChangeRequest('${id}','approved')">موافقة وتحديث</button><button type="button" class="secondary" onclick="openPartialChangeEdit('${id}')">تعديل الموعد</button>`;else if(isPendingBookingMessage(item))actionButtons=`<button type="button" onclick="approvePendingAppointment('${id}')">موافقة على الموعد</button><button type="button" class="secondary" onclick="openPartialChangeEdit('${id}')">تعديل الموعد</button>`;return`<div class="message-actions">${actionButtons}<button type="button" class="danger message-delete-button" onclick="deleteOwnerMessage('${item._id}')">حذف الرسالة</button></div>`}
async function deleteOwnerMessage(id){if(!confirm('هل تريد حذف هذه الرسالة؟'))return;try{await api('/messages/'+id,{method:'DELETE'});await loadOwnerMessages()}catch(e){alert(e.message)}}
async function deleteTreatedMessages(){if(!confirm('هل تريد حذف جميع رسائل طلبات التعديل التي تمت معالجتها؟'))return;try{const result=await api('/messages/treated/all',{method:'DELETE'});await loadOwnerMessages();if(!result.deleted)alert('لا توجد رسائل معالجة للحذف')}catch(e){alert(e.message)}}
async function loadOwnerMessages(){try{await syncExistingOwnerPush();const d=await api('/messages');$('ownerMessagesBadge').textContent=d.unreadCount>99?'99+':String(d.unreadCount);$('ownerMessagesBadge').classList.toggle('hidden',!d.unreadCount);$('ownerMessagesList').innerHTML=d.data.length?d.data.map(item=>`<article class="message-item ${item.readAt?'':'unread'}"><div><h3>${safe(item.title)}</h3><time>${new Date(item.createdAt).toLocaleString('ar',{timeZone:'Asia/Jerusalem'})}</time></div><p>${safe(item.body)}</p>${ownerMessageActions(item,d.data)}</article>`).join(''):'<p class="muted empty-messages">لا توجد رسائل بعد</p>'}catch(e){console.error('Owner messages load failed:',e)}}
async function refreshOwnerMessages(){await loadAppointments();await loadOwnerMessages()}
async function refreshOwnerData(){const button=$('ownerRefreshButton');button.disabled=true;button.classList.add('is-refreshing');try{await Promise.all([loadCustomers(),loadServices(),loadHours()]);await loadAppointments();await loadOwnerMessages()}catch(e){alert(e.message)}finally{button.disabled=false;button.classList.remove('is-refreshing')}}
async function openOwnerMessages(){await refreshOwnerMessages();$('ownerMessagesPanel').classList.remove('hidden');document.body.classList.add('messages-open');try{await api('/messages/read-all',{method:'PUT'});$('ownerMessagesBadge').classList.add('hidden');$('ownerMessagesList').querySelectorAll('.unread').forEach(item=>item.classList.remove('unread'))}catch(e){console.error(e)}}
function closeOwnerMessages(){$('ownerMessagesPanel').classList.add('hidden');document.body.classList.remove('messages-open')}
function showOwnerApp(){const welcome=$('ownerWelcomeView');welcome.classList.add('welcome-leaving');setTimeout(()=>{welcome.classList.add('hidden');$('ownerAppContent').classList.remove('hidden')},360)}
function setupCollapsibleSections(){document.querySelectorAll('.collapsible-card').forEach(card=>{const key=`owner-section-${card.dataset.section}`,button=card.querySelector('.collapse-button');const setCollapsed=collapsed=>{card.classList.toggle('is-collapsed',collapsed);button.textContent=collapsed?'+':'−';button.setAttribute('aria-expanded',String(!collapsed));button.setAttribute('aria-label',`${collapsed?'فتح':'طي'} ${card.querySelector('h2').textContent}`)};setCollapsed(localStorage.getItem(key)==='collapsed');button.addEventListener('click',()=>{const collapsed=!card.classList.contains('is-collapsed');setCollapsed(collapsed);localStorage.setItem(key,collapsed?'collapsed':'open')})})}
document.addEventListener('DOMContentLoaded',async()=>{setupCollapsibleSections();$('ownerEnterButton').onclick=showOwnerApp;if(sessionStorage.getItem('skipDashboardIntro')==='1'){sessionStorage.removeItem('skipDashboardIntro');$('ownerWelcomeView').classList.add('hidden');$('ownerAppContent').classList.remove('hidden')}$('filterDate').value=getTodayInJerusalem();updateAppointmentFilterControls();try{const me=await api('/auth/me');if(me.user.role!=='owner')location.href='index.html';await Promise.all([loadCustomers(),loadServices(),loadHours()]);await loadAppointments();await loadOwnerMessages()}catch(e){console.error(e)}$('logout').onclick=()=>{localStorage.removeItem('token');location.href='index.html'};$('ownerMessagesButton').onclick=openOwnerMessages;$('closeOwnerMessages').onclick=closeOwnerMessages;$('ownerMessagesPanel').addEventListener('click',event=>{if(event.target===$('ownerMessagesPanel'))closeOwnerMessages()});navigator.serviceWorker?.addEventListener('message',event=>{if(event.data?.type==='fadila-message')refreshOwnerMessages()});$('createCustomer').onclick=createCustomer;$('addService').onclick=addService;$('manualService').onchange=loadSlots;$('manualDate').onchange=loadSlots;$('createAppointment').onclick=createAppointment;$('filterDate').onchange=()=>{updateAppointmentFilterControls();renderAppointments();decorateAllAppointmentDates()};$('showAllAppointments').onclick=toggleAllAppointments;$('timelineEditorButton').onclick=openTimeline;$('closeTimeline').onclick=closeTimeline;$('timelineModal').addEventListener('click',event=>{if(event.target===$('timelineModal'))closeTimeline()});$('saveHours').onclick=saveHours;$('enableNotifications').onclick=enablePush;$('testNotification').onclick=testPush;$('sendCustomerNotification').onclick=sendCustomerNotification});
